# Code 2
- Basic Imputation for Numerical and Categorial
- Logistic Model (Balanced/ Unbalanced)

## 1/ Import Libraries

In [1]:
#CodeSection1
from google.colab import drive
drive.mount('/mntDrive')

Mounted at /mntDrive

In [2]:
#CodeSection2
import pandas as pd

## 2/ Import Data

In [3]:
#CodeSection3
train = pd.read_csv("/mntDrive/MyDrive/__Data_Science/2 Cross Sell Prediction/input/train.csv")
test = pd.read_csv("/mntDrive/MyDrive/__Data_Science/2 Cross Sell Prediction/input/test.csv")

### Check Train Data

In [4]:
#CodeSection4
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381109 entries, 0 to 381108
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    381109 non-null  int64
 1   Gender                381109 non-null  object
 2   Age                   381109 non-null  int64
 3   Driving_License       381109 non-null  int64
 4   Region_Code           381109 non-null  float64
 5   Previously_Insured    381109 non-null  int64
 6   Vehicle_Age           381109 non-null  object
 7   Vehicle_Damage        381109 non-null  object
 8   Annual_Premium        381109 non-null  float64
 9   Policy_Sales_Channel  381109 non-null  float64
 10  Vintage               381109 non-null  int64
 11  Response              381109 non-null  int64
dtypes: float64(3), int64(6), object(3)
memory usage: 34.9+ MB

### Check Test Data

In [5]:
#CodeSection4
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127037 entries, 0 to 127036
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    127037 non-null  int64
 1   Gender                127037 non-null  object
 2   Age                   127037 non-null  int64
 3   Driving_License       127037 non-null  int64
 4   Region_Code           127037 non-null  float64
 5   Previously_Insured    127037 non-null  int64
 6   Vehicle_Age           127037 non-null  object
 7   Vehicle_Damage        127037 non-null  object
 8   Annual_Premium        127037 non-null  float64
 9   Policy_Sales_Channel  127037 non-null  float64
 10  Vintage               127037 non-null  int64
dtypes: float64(3), int64(5), object(3)
memory usage: 10.7+ MB

### We Combine both Datasets to perform Missing Value Imputation

In [6]:
#CodeSection6
all_data = [train, test]

In [7]:
#CodeSection7
# Combine both using concat (with axis = 0) to check Missing Value
pd.concat([train, test], axis = 0).isnull().sum()

id                           0
Gender                       0
Age                          0
Driving_License              0
Region_Code                  0
Previously_Insured           0
Vehicle_Age                  0
Vehicle_Damage               0
Annual_Premium               0
Policy_Sales_Channel         0
Vintage                      0
Response                127037
dtype: int64

## 3/ Impute Numerical Variables
- Impute all Numerical Variables

### Variable/Feature 1

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

### Variable/Feature 2

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

### Variable/Feature 3

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

### Variable/Feature 4

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

## 4/ Impute Categorical Variables
- Impute all Numerical Variables

### Categorical Variable/Feature 1

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
<Write your code here>

### Categorical Variable/Feature 2

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
<Write your code here>

SyntaxError: ignored

### Categorical Variable/Feature 3

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
<Write your code here>

### Categorical Variable/Feature 4

In [ ]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
<Write your code here>

## 5/ Now Re Check all of them

In [8]:
#CodeSection10
# Combine both to check Missing Value
pd.concat([train, test], axis = 0).isnull().sum()

id                           0
Gender                       0
Age                          0
Driving_License              0
Region_Code                  0
Previously_Insured           0
Vehicle_Age                  0
Vehicle_Damage               0
Annual_Premium               0
Policy_Sales_Channel         0
Vintage                      0
Response                127037
dtype: int64

## 6/ Prepare Data for Model Model

In [10]:
train.head()

   id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0   1    Male   44  ...                  26.0      217         1
1   2    Male   76  ...                  26.0      183         0
2   3    Male   47  ...                  26.0       27         1
3   4    Male   21  ...                 152.0      203         0
4   5  Female   29  ...                 152.0       39         0

[5 rows x 12 columns]

In [9]:
#CodeSection11
# Check first 5 rows of Test Dataset
test.head()

       id Gender  Age  ...  Annual_Premium  Policy_Sales_Channel  Vintage
0  381110   Male   25  ...         35786.0                 152.0       53
1  381111   Male   40  ...         33762.0                   7.0      111
2  381112   Male   47  ...         40050.0                 124.0      199
3  381113   Male   24  ...         37356.0                 152.0      187
4  381114   Male   27  ...         59097.0                 152.0      297

[5 rows x 11 columns]

In [12]:
#CodeSection12
# Divide Data into X and y
X = train.drop(['id','Response'], axis=1)
y = train['Response']

### Create Dummy Variables for  Categorical Variables

In [13]:
#CodeSection13
# Create Dummy Variables
X = pd.get_dummies(X)

In [14]:
#CodeSection14
# Check first 5 rows of X
X.head()

   Age  Driving_License  ...  Vehicle_Damage_No  Vehicle_Damage_Yes
0   44                1  ...                  0                   1
1   76                1  ...                  1                   0
2   47                1  ...                  0                   1
3   21                1  ...                  1                   0
4   29                1  ...                  1                   0

[5 rows x 14 columns]

## 7/ Build Model

In [15]:
#CodeSection15
#Start by importing LogisticRegression 
from sklearn.linear_model import LogisticRegression

#Initialize LogisticRegression
clf = LogisticRegression(max_iter=1000)

In [16]:
#CodeSection16
# Fit Model
model = clf.fit(X,y)

### Check Accuracy of Model on Train Data

In [17]:
#CodeSection17
# Predict on Train Data and check predictions
y_pred = model.predict(X)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

### We can use a Accuracy Function from Metrics

In [18]:
#CodeSection17
# Import accuracy_score 
from sklearn.metrics import accuracy_score

In [19]:
#CodeSection18
# Get Actual Predictions
y_true = y

In [20]:
#CodeSection19
# Compare True values versus prediction we made
print(f" Train Accuracy : {accuracy_score(y_true, y_pred):0.1%}")

 Train Accuracy : 87.7%

## 8/ Prediction and Submission

### Predict

In [21]:
#CodeSection20
# Get X variables from the Test Dataset
X_test = test.drop(['id'], axis=1)

In [22]:
#CodeSection21
#Covert to Dummies
X_test = pd.get_dummies(X_test)

In [23]:
#CodeSection22
# Predict (Y/N) on X Variables of Test Dataset
X_test_pred = model.predict(X_test)

### Import Sample Submission

In [24]:
#CodeSection23
sample_submission = pd.read_csv('/mntDrive/MyDrive/__Data_Science/2 Cross Sell Prediction/input/sample_submission.csv')
sample_submission.head()

       id  Response
0  381110         0
1  381111         0
2  381112         0
3  381113         0
4  381114         0

### Create a Submission

In [25]:
#CodeSection24
submission = pd.DataFrame({
    'id' : test['id'],
    'Response' : X_test_pred
})

### Export Submission File

In [27]:
#CodeSection25
submission.to_csv('/mntDrive/MyDrive/__Data_Science/2 Cross Sell Prediction/output/O2_LR_Basic_Impute.csv', index = False)

In [ ]:
# LB Accuracy : <Write your score here>